// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PonySample.CustomGenerators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Microsoft.EntityFrameworkCore;
    using PonyDbContextScaffold.GenCustomClasses;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "S:\w\PonySample\CustomGenerators\SampleGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SampleGenerator : PonyDbContextScaffold.GenCustomClasses.EntityT4GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n\r\n\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentMod" +
                    "el;\r\nusing System.Drawing;\r\nusing System.Data;\r\nusing System.Text;\r\nusing System" +
                    ".Windows.Forms;\r\n\r\nnamespace CodeGenApp\r\n{\r\n    public partial class ");
            
            #line 23 "S:\w\PonySample\CustomGenerators\SampleGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("EntityEditor : UserControl\r\n    {\r\n \r\n\r\n            ");
            
            #line 27 "S:\w\PonySample\CustomGenerators\SampleGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenColumns ()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            ");
            
            #line 29 "S:\w\PonySample\CustomGenerators\SampleGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PerPropertyGen("this.Url,", "Url", p => p.Name )));
            
            #line default
            #line hidden
            this.Write("});\r\n\r\n\r\n\r\n    }\r\n}\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 38 "S:\w\PonySample\CustomGenerators\SampleGenerator.tt"





        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
